const projects=[
 /* Temporarily hidden Featured Project — restore this block when Aatma is ready to showcase.
 {id:'aatma',category:'Featured Project',name:'Aatma (Working Title)',status:'Coming Soon',type:'Featured Project',engine:'Unreal Engine 5',role:'Gameplay Programmer',platform:'PC',tags:['C++','Blueprint','Gameplay Architecture'],summary:'An independent third-person adventure game focused on exploration, environmental puzzles, and immersive world building.'},
 */
 {id:'rts-military-game',category:'Projects',name:'RTS Military Game',type:'Commercial Project',engine:'Unreal Engine',role:'Gameplay Programmer',platform:'PC',tags:['C++','RTS','Vehicle Physics'],summary:'A military real-time strategy game combining RTS gameplay with direct third-person control of individual units and vehicles.'},
 {id:'political-strategy-game',category:'Projects',name:'Political Strategy Game',type:'Commercial Project',engine:'Unreal Engine 4',role:'Gameplay Programmer',platform:'PC',tags:['Strategy','UI','Simulation'],summary:'A political strategy game focused on resource management, decision-making, interactive UI, and simulation mechanics.'},
 {id:'tower-defense-game',category:'Projects',name:'Tower Defense Game',type:'Commercial Project',engine:'Unreal Engine 4',role:'Gameplay Programmer',platform:'PC',tags:['Tower Defense','Spells','Strategy'],summary:'Tower defense gameplay featuring enemy waves, tower combat, spell systems, upgrade mechanics, and strategic play.'},
 {id:'snow-survival',category:'Projects',name:'Snow Survival',type:'Commercial Project',engine:'Unity',role:'Developer',platform:'PC',tags:['C#','Survival','Open World'],summary:'A survival exploration game featuring dog-sled traversal, bow combat, fishing mechanics, and an open snowy environment.'},
 {id:'hat-configurator',category:'Projects',name:'3D Hat Configurator',type:'Interactive Application',engine:'Unity',role:'Developer',platform:'WebGL',tags:['Web','3D UI','Materials'],summary:'A WebGL-deployed 3D product configurator with dynamic materials, custom text, interactive 3D preview, and product configuration.'},
 {id:'go-emoji-go',category:'Projects',name:'Go Emoji Go: The Maze',type:'Commercial Project',engine:'Unity',role:'Developer',platform:'Android',tags:['C#','Mobile','Combat'],summary:'A mobile game featuring character selection, exploration, combat, shooting mechanics, and progressive levels.'},
 {id:'race-of-difficulty',category:'Projects',name:'Race of Difficulty',type:'Personal Project',engine:'Unity',role:'Developer',platform:'Android',tags:['Published','Mobile'],summary:'An online multiplayer ball-racing game featuring challenging tracks, power-ups, and customizable ball skins.'},
 {id:'virus-winner',category:'Projects',name:'Virus Winner',type:'Personal Project',engine:'Unity',role:'Developer',platform:'Android',tags:['Published','Mobile'],summary:'An endless runner featuring virus hazards, power-ups, planetary environments, and progression-based gameplay.'},
 {id:'yatri',category:'Projects',name:'Yatri',type:'Personal Project',engine:'Unity',role:'Developer',platform:'Android',tags:['Published','Mobile'],summary:'A 2D puzzle and passenger-management game focused on strategic movement, seating, and increasingly challenging levels.'}
];
const groups=document.querySelector('#project-groups');
if(groups){[...new Set(projects.map(p=>p.category))].forEach(category=>{const section=document.createElement('section');section.className='project-group';section.innerHTML=`<h3>${category}</h3><div class="project-grid">${projects.filter(p=>p.category===category).map(p=>`<article class="project-card ${p.id==='aatma'?'featured':''} ${p.id==='rts-military-game'?'rts-featured':''}"><div class="thumbnail"><span>${p.status||p.type}</span></div><div class="card-body"><h4>${p.name}</h4><div class="card-metadata"><span>${p.type}</span><span>${p.engine}</span><span>${p.role}</span><span>${p.platform}</span></div><div class="tags">${p.tags.map(t=>`<span>${t}</span>`).join('')}</div><p>${p.summary}</p><a class="text-link" href="project.html?id=${p.id}">View Project <span>&nearr;</span></a></div></article>`).join('')}</div>`;groups.append(section)})}
const nav=document.querySelector('.nav'),menu=document.querySelector('.menu');menu?.addEventListener('click',()=>{const open=nav.classList.toggle('open');menu.setAttribute('aria-expanded',open);menu.textContent=open?'Close':'Menu'});document.querySelectorAll('nav a').forEach(a=>a.addEventListener('click',()=>{nav?.classList.remove('open');if(menu){menu.textContent='Menu';menu.setAttribute('aria-expanded','false')}}));
